### ISSUE TITLE
logarithm function not supported!

### ISSUE THREAD

**Issue by hxrshu** [ChristopherChudzicki/math3d-react#263]
Hey,

I am trying to graph `x^2/ln(y)` but it does not accept the natural log into it.

Other than that, THANK YOU SO MUCH FOR THIS GRAPHER!! Desperately neded this!

**Comment by stardust66** [comment]
Hi,

Not the author but he used to be my math teacher. Thanks for using math3d! I believe the natural log function is just `log`, so that should work. As previous issues have pointed out, we do need to work on adding documentation and improving discoverability. In the mean time, you can check https://mathjs.org/docs/reference/functions.html#arithmetic-functions for functions that math3d supports.

**Comment by hxrshu** [comment]
Hello,

Yes I did try that, doesn't seem to work! Here's a screensnip

![image](https://user-images.githubusercontent.com/69312581/89561525-e883fc00-d818-11ea-8ad3-36d587f778c2.png)

**Comment by hxrshu** [comment]
Oh, looks like it was not going through because I didn't put the brackets around the input to the `log`! Thanks and sorry for wasting your time!

Once again, I am so grateful to Math3D. Please convey my thoughts to your teacher if you can, he's been such a lifesaver!

**Comment by stardust66** [comment]
Glad you’ve got it working! We will definitely work on documenting all the features to make math3d easier to use. Thank you for your feedback! I’m happy that you enjoy using math3d. It’s certainly helped me a lot and made multi-variable calculus a lot more fun.
